// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookInput struct {
	Name        string `json:"name"`
	Author      string `json:"author"`
	Publication string `json:"publication"`
}

type Mutation struct {
}

type Query struct {
}
